platform :ios, '7.1'
pod 'ACSimpleKeychain', '~> 0.3'
pod 'DALinedTextView', '~> 0.0.1'
pod 'ObjectiveRecord', '~> 1.5'
pod 'BDBSplitViewController', '~> 1.3'
pod 'UIImage+PDF', '~> 1.1'
pod 'vfrReader', '~> 2.7'
pod 'FXReachability', '~> 1.3.1'
pod 'skpsmtpmessage'
pod 'INTULocationManager', '~> 1.1.0'
pod 'SVProgressHUD', :head
pod 'RestKit', '~> 0.24'